CREATE TABLE "User" (
  "UserID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Email" varchar(100),
  "FullName" text,
  "Password" varchar(60),
  "googleId" text,
  "Job" text,
  "Department" text,
  "Faculty" text,
  "Workplace" text,
  "Tel" varchar(10),
  "Usageformat" varchar(10),
  "ImgE_KYC_path" text,
  "E_KYC" varchar(20),
  "TypesID_User" int
);

CREATE TABLE "Role" (
  "TypesID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "TypesName" varchar(40),
  "LimitSub" int,
  "LimitQue" int
);

CREATE TABLE "Request" (
  "RequestID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "UserID_Request" int,
  "ImgRequest_path" text,
  "Status_Request" int
);

CREATE TABLE "CheckScore" (
  "ScoreID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "UserID_Score" int,
  "ActivateKey_Score" text
);

CREATE TABLE "Subject" (
  "SubID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "UserID_Sub" int,
  "SubjectID" varchar(20),
  "SubName" varchar(100),
  "Year" varchar(10),
  "Semester" varchar(10)
);

CREATE TABLE "Exam" (
  "ExamID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "SubID_exam" int,
  "NameExam" text,
  "ExamNo" int,
  "NumExam" int,
  "SetExam" int,
  "ImgAnswerS_format_path" text,
  "Std_csv_path" text
);

CREATE TABLE "ExamAnswers" (
  "ExamAnswersID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ExamID_Ans" int,
  "SetExamAns" int,
  "ScoringCriteria" text,
  "PapeAns_path" text
);

CREATE TABLE "Examinformation" (
  "ExaminfoID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ExamID_info" int,
  "StdID" varchar(20),
  "SubIDStd" varchar(20),
  "ExamSeatNumber" varchar(20),
  "SetExamInfo" int,
  "Section" varchar(20),
  "Score" int,
  "Correct" int,
  "Wrong" int,
  "Unresponsive" int,
  "AnsChoiceStd" text,
  "ActivateKey_Exan" varchar(100),
  "ImgAnsStd_path" text
);

CREATE TABLE "Lesson" (
  "LessonID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "UserID_Lesson" int,
  "NameLesson" text,
  "InfoLesson" text
);

CREATE TABLE "SubLesson" (
  "SubLessonID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "LessonID_SubLessonID" int,
  "NumLesson" text,
  "NameLesson" text,
  "InfoLesson" text
);

CREATE TABLE "LessonAnswer" (
  "LessonAndAnswer" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ExamAnswersID_LesAns" int,
  "SubLessonID_LesAns" int,
  "ChoiceLesson" text
);

CREATE TABLE "QueSheet" (
  "QueSheetID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "UserID_Que" int,
  "QueSheetName" text,
  "QueSheetTopicName" text,
  "DetailsLineOne" text,
  "DetailsLinetwo" text,
  "Explanation" text,
  "Symbolposition" varchar(10),
  "ImgLogoQueSheet_path" text,
  "ImgQueSheet_path" text,
  "ActivateKey_Que" text,
  "DateTimeStart" datetime,
  "DateTimeEnd" datetime,
  "StatusQueSheet" varchar(10)
);

CREATE TABLE "QueHeadDetails" (
  "QueHeadDetailsID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "QueSheetID_Head" int,
  "QueHead1" text,
  "QueHead2" text,
  "QueHead3" text,
  "QueHead4" text,
  "QueHead5" text
);

CREATE TABLE "QueTopicDetails" (
  "QueTopicDetailsID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "QueSheetID_Topic" int,
  "QueTopicNum" text,
  "QueTopicDetails" text,
  "QueTopicFormat" text,
  "QueTopicType" text
);

CREATE TABLE "Queinformation" (
  "QueinfoID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "QueSheetID_QueInfo" int,
  "AnsQueHead" text,
  "AnsQueTopic" text,
  "ImgAnsStd_path" text,
  "Status_QueInfo" varchar(10)
);

ALTER TABLE "User" ADD FOREIGN KEY ("TypesID_User") REFERENCES "Role" ("TypesID");

ALTER TABLE "Request" ADD FOREIGN KEY ("UserID_Request") REFERENCES "User" ("UserID");

ALTER TABLE "CheckScore" ADD FOREIGN KEY ("UserID_Score") REFERENCES "User" ("UserID");

ALTER TABLE "Subject" ADD FOREIGN KEY ("UserID_Sub") REFERENCES "User" ("UserID");

ALTER TABLE "Exam" ADD FOREIGN KEY ("SubID_exam") REFERENCES "Subject" ("SubID");

ALTER TABLE "ExamAnswers" ADD FOREIGN KEY ("ExamID_Ans") REFERENCES "Exam" ("ExamID");

ALTER TABLE "Examinformation" ADD FOREIGN KEY ("ExamID_info") REFERENCES "Exam" ("ExamID");

ALTER TABLE "Lesson" ADD FOREIGN KEY ("UserID_Lesson") REFERENCES "User" ("UserID");

ALTER TABLE "SubLesson" ADD FOREIGN KEY ("LessonID_SubLessonID") REFERENCES "Lesson" ("LessonID");

ALTER TABLE "LessonAnswer" ADD FOREIGN KEY ("ExamAnswersID_LesAns") REFERENCES "ExamAnswers" ("ExamAnswersID");

ALTER TABLE "LessonAnswer" ADD FOREIGN KEY ("SubLessonID_LesAns") REFERENCES "SubLesson" ("SubLessonID");

ALTER TABLE "QueSheet" ADD FOREIGN KEY ("UserID_Que") REFERENCES "User" ("UserID");

ALTER TABLE "QueHeadDetails" ADD FOREIGN KEY ("QueSheetID_Head") REFERENCES "QueSheet" ("QueSheetID");

ALTER TABLE "QueTopicDetails" ADD FOREIGN KEY ("QueSheetID_Topic") REFERENCES "QueSheet" ("QueSheetID");

ALTER TABLE "Queinformation" ADD FOREIGN KEY ("QueSheetID_QueInfo") REFERENCES "QueSheet" ("QueSheetID");
